name: Ensure WP Fork Exists and Sync

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Run every hour
  workflow_dispatch: # Allow manual sync trigger

jobs:
  sync-wp:
    runs-on: ubuntu-latest

    steps:
    - name: Set Repository Names
      run: |
        echo "SRC_REPO=${SRC_REPO:-WordPress/WordPress}" >> $GITHUB_ENV
        echo "DST_REPO=${DST_REPO:-WP}" >> $GITHUB_ENV

    - name: Clear Existing GitHub CLI Credentials
      run: |
        gh auth logout --hostname github.com || true

    - name: Authenticate with GitHub CLI
      run: |
        echo "${{ secrets.BOT_TOKEN }}" | gh auth login --with-token
        gh auth status

    - name: Create Fork if Missing
      run: |
        if ! gh repo view $DST_REPO > /dev/null 2>&1; then
          gh repo fork $SRC_REPO --clone=false --fork-name $DST_REPO --include-branches
          echo "Fork created."
        fi

    - name: Sync WordPress Fork
      run: gh repo sync $DST_REPO --force
