name: Ensure WP Fork Exists and Sync

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Run every hour
  workflow_dispatch: # Allow manual sync trigger

jobs:
  sync-wp:
    runs-on: ubuntu-latest
    environment: prod

    steps:
    - name: Set Repository Names
      run: |
        echo "SRC_REPO=${SRC_REPO:-WordPress/WordPress}" >> $GITHUB_ENV
        echo "DST_ORG=${DST_ORG:-WebPublishOrg}" >> $GITHUB_ENV
        echo "DST_REPO=${DST_REPO:-WP}" >> $GITHUB_ENV

    - name: Create Fork if Missing
      env:
        GH_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: |
        if ! gh repo view $DST_ORG/$DST_REPO > /dev/null 2>&1; then
          gh repo fork $SRC_REPO --clone=false --org $DST_ORG --fork-name $DST_REPO
          echo "Fork created."
        else
          echo "Fork already exists."
        fi

    - name: Fetch and Push All Branches
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: |
        git clone https://github.com/$DST_ORG/$DST_REPO.git
        cd $DST_REPO
        git remote add upstream https://github.com/$SRC_REPO.git
        git fetch upstream
        git remote set-url origin https://x-access-token:${{ secrets.BOT_TOKEN }}@github.com/$DST_ORG/$DST_REPO.git
        for branch in $(git branch -r | grep 'upstream/' | grep -v 'HEAD' | grep -v 'tags/' | sed 's|upstream/||'); do
          if git show-ref --verify --quiet refs/heads/$branch; then
            git checkout $branch
          else
            git checkout -b $branch upstream/$branch
          fi
          git push origin refs/heads/$branch --force
        done

    - name: Fetch and Push All Tags
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: |
        cd $DST_REPO
        git fetch upstream --tags
        git push origin --tags --force
